### ISSUE TITLE
Can't build with the provided clang++ compiler

### ISSUE THREAD

**Issue by winux138** [trailofbits/magnifier#13]
As mentioned in the readme, I first fetched the cxx-common with  `scripts/fetch-cxx-common.sh` then exported `INSTALL_DIR` and `VCPKG_ROOT` and ran `scripts/build-preset.sh`.

You'll find attached my `magnifier-build.log`, the issue seems to be that it's not building with the `c++20` flag, as it's missing features introduced in `c++17`.

Maybe the issue should be posted on the cxx-common repo ?

[magnifier-build.log](https://github.com/trailofbits/magnifier/files/9433309/magnifier-build.log)

**Comment by pgoodman** [comment]
@winux138 can you try adding an `#include <optional>` to `magnifier/BitcodeExplorer.h`, and if that works, submit a PR?

**Comment by winux138** [comment]
@pgoodman It did fix the issue :+1:
