### ISSUE TITLE
Adding documentation and tutorial explaining the REPL interface

### ISSUE THREAD

**Issue by surovic** [trailofbits/magnifier#6]
First off, I think the REPL interface is great and I can definitely see this going places! Now given this [clip](https://asciinema.org/a/QCO3qAzTZyud2pWWrRA8y0TdC) I think it would be great if there was some commentary that would explain what can be seen in the interface and how it relates to the underlying LLVM bitcode module.

For example, what does `91|91` in the leftmost column on a line in the terminal mean? And how does `91|91` change to `160|91` when I do a substitution? What does a substitution do with the bitcode module as a whole?

A video or even a textual tutorial or README would be great!

**Comment by pgoodman** [comment]
The blog post explains this. I'll add a readme link.
